
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projet-citoyen-2024
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: projet-citoyen
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pcitoyen@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secretpassword
    ports:
      - "5050:80"

