import type {Metadata} from "next";
import {Outfit} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import Topbar from "@/components/Topbar/Topbar";
import {ReactNode} from "react";

const inter = Outfit({subsets: ["latin"], variable: "--font-sans"});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="fr">
            <body className={cn(
                "flex flex-col min-h-screen bg-background font-sans antialiased",
                inter.variable
            )}>
            <Topbar/>
            {children}
            </body>
        </html>
    );
}
