import type {Metadata} from "next";
import {Outfit} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import Topbar from "@/components/Topbar/Topbar";
import {ReactNode} from "react";
import Footer from "@/components/Footer/Footer";
import {SessionProvider} from "@/components/SessionProvider/SessionProvider";
import {getServerSession} from "next-auth";
import {authOptions} from "@/lib/authOptions";

const inter = Outfit({subsets: ["latin"], variable: "--font-sans"});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    const session = await getServerSession(authOptions)
    return (
        <html lang="fr">
        <body className={cn(
            "flex flex-col min-h-screen bg-background font-sans antialiased",
            inter.variable
        )}>
        <SessionProvider session={session}>
            <Topbar/>
            {children}
            <Footer/>
        </SessionProvider>
        </body>
        </html>
    );
}
