name: CICD
run-name: ${{ github.actor }} CICD
on: 
  push:
    branches:
      - develop
env:
  POSTGRES_PRISMA_URL: ${{ vars.POSTGRES_PRISMA_URL }}
  POSTGRES_URL_NON_POOLING: ${{ vars.POSTGRES_URL_NON_POOLING }}
  NEXT_PUBLIC_PUSHER_APP_KEY: ${{ vars.NEXT_PUBLIC_PUSHER_APP_KEY }}
  PUSHER_APP_ID: ${{ vars.PUSHER_APP_ID }}
  PUSHER_APP_SECRET: ${{ vars.PUSHER_APP_SECRET }}

jobs:
    build-project:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Install NPM dependencies
            run: npm install
          - name: Prisma generate
            run: npx prisma generate
          - name: Build project 
            run: npm run build
            
          #- run: sleep 20
          ## Commande pour lancer des test dans le futur avec JEST ?
          #- run: docker compose exec web npm run test
    
