name: CICD
run-name: ${{ github.actor }} CICD
on: 
  push:
    branches:
      - feat/mise-en-place-cicd-integration

env:
  NEXT_PUBLIC_PUSHER_APP_KEY: ${{ vars.NEXT_PUBLIC_PUSHER_APP_KEY }}
  PUSHER_APP_ID: ${{ vars.PUSHER_APP_ID }}
  PUSHER_APP_SECRET: ${{ vars.PUSHER_APP_SECRET }}

jobs:
  build-project:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.3-alpine3.20
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secretpassword
          POSTGRES_DB: projet-citoyen
        ports:
          - "5432:5432"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "POSTGRES_PRISMA_URL=postgres://postgres:secretpassword@localhost:5432/projet-citoyen" >> $GITHUB_ENV

      - name: Install NPM dependencies
        run: npm install

      - name: Install Prisma globally
        run: npm install -g prisma

      - name: Wait for PostgreSQL to be ready
        run: |
          sudo apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done

      - name: Prisma generate
        run: npx prisma generate

      - name: Apply Prisma migrations
        run: npx prisma migrate deploy

      - name: Copy seed data to PostgreSQL container
        run: docker cp script/db/seedData_01-07.sql postgres:/seedData_01-07.sql

      - name: Seed the database
        env:
          PGPASSWORD: secretpassword
        run: |
          psql -h localhost -p 5432 -U postgres -d projet-citoyen -f /seedData_01-07.sql

      - name: Verify data seeding
        env:
          PGPASSWORD: secretpassword
        run: |
          psql -h localhost -p 5432 -U postgres -d projet-citoyen -c "SELECT * FROM \"User\";"

      # Uncomment the next lines if you want to run tests with Jest
      # - name: Run tests
      #   run: npm run test
