name: CICD
run-name: ${{ github.actor }} CICD
on: 
  push:
    branches:
      - develop

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: docker compose up -d --build 
          #- run: sleep 20
          ## Commande pour lancer des test dans le futur avec JEST ?
          #- run: docker compose exec web npm run test
    
