name: CICD
run-name: ${{ github.actor }} CICD
on: 
  push:
    branches:
      - develop

jobs:
    build-project:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Install NPM dependencies
            run: npm install
          - name: Build project 
            run: npm run build
            
          #- run: sleep 20
          ## Commande pour lancer des test dans le futur avec JEST ?
          #- run: docker compose exec web npm run test
    
